apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-test-service-gcp-sg
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: dev
  source:
    path: services/app-test-service
    repoURL: https://github.com/awx-zorian/argo-stack.git
    targetRevision: HEAD
    helm:
      valueFiles:
        - values.yaml
        - dev/values.yaml
        - dev/gcp-sg-values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: dev
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true
    