apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ingress-nginx
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: infra
  source:
    path: deploy/static/provider/cloud/deploy.yaml
    repoURL: https://github.com/kubernetes/ingress-nginx.git
    targetRevision: controller-v0.44.0 # from https://kubernetes.github.io/ingress-nginx/deploy/#gce-gke
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      selfHeal: true
      prune: true