apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istio-all
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: infra
  source:
    path: appservices/common/istio
    repoURL: https://github.com/riveryc/argo-stack.git
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      selfHeal: true
      prune: false