apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: {{ required "service name missing" .Values.serviceName }}
spec:
  replicas: {{ .Values.replicaCount }}
  strategy:
    canary:
      canaryService: {{ required "service name missing" .Values.serviceName }}-preview
      steps:
        - setWeight: 20
        - pause: {}
        - setWeight: 40
        - pause: {duration: 10}
        - setWeight: 60
        - pause: {duration: 10}
        - setWeight: 80
        - pause: {duration: 10}
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: {{ required "service name missing" .Values.serviceName }}
  template:
    metadata:
      labels:
        app: {{ required "service name missing" .Values.serviceName }}
    spec:
      containers:
      - name: {{ required "service name missing" .Values.serviceName }}
      {{- if .Values.myEnv }}
        env:
        {{- range $k, $v := .Values.myEnv }}
          - name: {{ $k }}
            value: {{ required (printf "%s missing" $k) ($v.value | quote) }}
        {{- end }}
      {{- end }}
        image: {{ .Values.myimage }}
        imagePullPolicy: Always
        resources:
          limits:
            cpu: 2500m
            memory: 2Gi
          requests:
            cpu: 500m
            memory: 1Gi
      terminationMessagePath: /dev/termination-log
      terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      enableServiceLinks: true
      restartPolicy: Always
      serviceAccount: default
      serviceAccountName: default