apiVersion: v1
kind: Service
metadata:
  name: {{ required "service name missing" .Values.serviceName }}
spec:
  ports:
  - port: 80
    targetPort: http
    protocol: TCP
    name: http
  selector:
    app: {{ required "service name missing" .Values.serviceName }}