# Default values for helm-guestbook.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

myimage: asia.gcr.io/airwallex/app-validation-service:zrelease-1.7.0-SNAPSHOT
