apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rollouts-demo-bg
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: production
  source:
    path: appservices/domain/rollouts-demo-bg
    repoURL: https://github.com/riveryc/argo-stack.git
    targetRevision: ingress-preinstall
  destination:
    server: https://kubernetes.default.svc
    namespace: domain-bg
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
    - CreateNamespace=true