apiVersion: argoproj.io/v1alpha1
kind: Experiment
metadata:
  name: native-experiment
spec:
  duration: 5m
  templates:
  - name: purple
    replicas: 2
    minReadySeconds: 10
    selector:
      matchLabels:
        app: native-experiment
        color: purple
    template:
      metadata:
        labels:
          app: native-experiment
          color: purple
      spec:
        containers:
        - name: native-experiment
          image: argoproj/rollouts-demo:purple
          imagePullPolicy: Always
          ports:
          - name: http
            containerPort: 8080
            protocol: TCP
  - name: orange
    minReadySeconds: 10
    replicas: 2
    selector:
      matchLabels:
        app: native-experiment
        color: orange
    template:
      metadata:
        labels:
          app: native-experiment
          color: orange
      spec:
        containers:
        - name: native-experiment
          image: argoproj/rollouts-demo:bad-orange # we are using a "bad" image to make sure the experiment will fail
          imagePullPolicy: Always
          ports:
          - name: http
            containerPort: 8080
            protocol: TCP

  analyses:
  - name: purple
    templateName: http-benchmark
    args: [{name: host, value: purple}]
  - name: orange
    templateName: http-benchmark
    args: [{name: host, value: orange}]