
serviceName: app-moneyflow-service
servicePort: 9200

image:
  repository: asia.gcr.io/airwallex/moneyflow-services
  tag:

replicaCount: 3

cloudProvider:
  platform:
  region:

resources:
  limits:
    cpu: 2500m
    memory: 2Gi
  requests:
    cpu: 500m
    memory: 1Gi

environment:

secretEnvironment: