apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ required "service name is missing" .Values.serviceName }}
  annotations:
    # cert-manager.io/cluster-issuer: letsencrypt-prod
    # kubernetes.io/tls-acme: "true"
    kubernetes.io/ingress.class: nginx
spec:
  rules:
  - host: {{ required "service name is missing" .Values.serviceName }}.{{ required "domain is missing" .Values.domainName }}.{{ required "cloud platform is missing" .Values.cloudPlatform }}-{{ required "region is missing" .Values.cloudRegion }}.{{ required "env is missing" .Values.cloudEnvironment }}.awx.im
    http:
      paths:
      - backend:
          serviceName: {{ required "service name is missing" .Values.serviceName }}
          servicePort: http
        path: /
  tls:
  - hosts:
    - "*.{{ required "domain is missing" .Values.domainName }}.{{ required "cloud platform is missing" .Values.cloudPlatform }}-{{ required "region is missing" .Values.cloudRegion }}.{{ required "env is missing" .Values.cloudEnvironment }}.awx.im"
    secretName: wildcard-{{ required "domain is missing" .Values.domainName }}-{{ required "cloud platform is missing" .Values.cloudPlatform }}-{{ required "region is missing" .Values.cloudRegion }}-{{required "env is missing" .Values.cloudEnvironment}}-awx-im-tls