java-service:
  serviceName: apprefdataservice
  servicePort: 9300

  image:
    repository: asia.gcr.io/airwallex/refdata-service
    tag:

  replicaCount: 3

  resources:
    limits:
      cpu: 2500m
      memory: 2Gi
    requests:
      cpu: 500m
      memory: 1Gi

  environment:

  secretEnvironment: