# Default values for helm-guestbook.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 3

myimage:

serviceName: app-test-service

myEnv:
  AWX_DATABASE_PASSWORD:
    value:
  AWX_ID_REDIS_PASSWORD:
    value:
  AWX_DATABASE_URL:
    value:
  AWX_DATABASE_USERNAME:
    value:
  AWX_ID_REDIS_ADDRESS:
    value:
  AWX_ID_REDIS_PORT:
    value:
  AWx_ID_REDIS_DB:
    value:
  SERVER_PORT:
    value: "8080"
