
serviceName: app-test-service

image:
  repository: argoproj/rollouts-demo
  tag:

replicaCount: 3

cloudProvider:
  platform:
  region:

resources:
  limits:
    cpu: 2500m
    memory: 2Gi
  requests:
    cpu: 500m
    memory: 1Gi

environment:
  AWX_DATABASE_PASSWORD:
    value:
  AWX_ID_REDIS_PASSWORD:
    value:
  AWX_DATABASE_URL:
    value:
  AWX_DATABASE_USERNAME:
    value:
  AWX_ID_REDIS_ADDRESS:
    value:
  AWX_ID_REDIS_PORT:
    value:
  AWx_ID_REDIS_DB:
    value:
  SERVER_PORT:
    value: "8080"
