apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: {{ required "service name is missing" .Values.serviceName }}
spec:
  replicas: {{ .Values.replicaCount }}
  strategy:
    canary:
      canaryService: {{ required "service name is missing" .Values.serviceName }}-preview
      steps:
        - setWeight: 20
        - pause: {}
        - setWeight: 40
        - pause: {duration: 10}
        - setWeight: 60
        - pause: {duration: 10}
        - setWeight: 80
        - pause: {duration: 10}
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: {{ required "service name is missing" .Values.serviceName }}
  template:
    metadata:
      labels:
        app: {{ required "service name is missing" .Values.serviceName }}
    spec:
      containers:
      - name: {{ required "service name is missing" .Values.serviceName }}
{{- if .Values.secretEnvironment }}
        envFrom:
          - secretRef:
              name: {{ .Values.secretEnvironment }}
{{- end }}
{{- if .Values.environment }}
        env:
{{- range $k, $v := .Values.environment }}
          - name: {{ $k }}
            value: {{ required (printf "%s missing" $k) ($v.value | quote) }}
{{- end }}
{{- end }}
        image: {{ required "image repository is missing" .Values.image.repository }}:{{ required "image tag is missing" .Values.image.tag }}
        imagePullPolicy: Always
{{- if .Values.resources }}
        resources:
{{ toYaml .Values.resources | indent 10 }}
{{- else }}
{{ fail "no resource definition" }}
{{- end }}
      terminationMessagePath: /dev/termination-log
      terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      enableServiceLinks: true
      restartPolicy: Always
      serviceAccount: default
      serviceAccountName: default